# This file describes an application. You can have multiple applications
# in the same project.


# The name of this app. Must be unique within a project.
name: mymagento
type: php:8.0

# 1. Change flavor to none.
build:
    flavor: none

# 2. Add composer ^2.0 as a php dependency.
dependencies:
    php:
        composer/composer: '^2.0'

# 3. Add a build hook to run the build tasks using Composer 2.x.

runtime:
    extensions:
        - xsl
        - newrelic
        - sodium

# The configuration of app when it is exposed to the web.
web:
    locations:
        "/":
            root: "web"
            allow: true
            scripts: true
            passthru: "/index.html"
            index:
                - index.html
            expires: -1
hooks:
    build: |
        set -e
        composer --no-ansi --no-interaction install --no-progress --prefer-dist --optimize-autoloader
    deploy: |
        echo "Deploy"
        rm -rf var/**
        rm -rf app/etc/**
        rm -rf pub/media/**
        rm -rf pub/static/**

mounts:
    "var": "shared:files/var"
    "app/etc": "shared:files/etc"
    "pub/media": "shared:files/media"
    "pub/static": "shared:files/static"

# The size of the persistent disk of the application (in MB).
disk: 2048
